package com.timebuddy.models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Represents an event that occurs on a specific date in the month.
 * This class is mapped to the "monthly_event" table in the database.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "monthly_event") // Specifies the table name for this entity
public class MonthlyEvent {

    /**
     * The unique ID for this event.
     * This will be auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Automatically generates an ID
    private Long eventId;

    /**
     * A description of the event.
     */
    private String eventDescription;

    /**
     * The date this event occurs.
     */
    private LocalDate eventDate;
}
